name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: "none"
version: 2.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.7.1
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  intl: ^0.20.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.6.1
  force_update_helper: ^0.2.1
  url_launcher: ^6.3.1
  firebase_ui_oauth_google: ^1.4.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  # a tool for running code generators
  build_runner: ^2.4.15
  # the code generator
  riverpod_generator: ^2.6.5
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.5
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
    - assets/habit-tracking.svg
    - .env
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
